version: "3.2"

services:
  frontend:
    build: ./example-frontend
    ports:
      - 5000:5000

  backend:
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=secret
    depends_on:
      - db

  redis:
    image: redis:alpine
    volumes:
      - ./database_redis:/data

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database_postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80